services:
  audit:
    build:
      context: ../
      dockerfile: services/audit/dockerfile
    ports:
      - '${AUDIT_SERVICE}:${AUDIT_SERVICE}'
    env_file:
      - .env
    networks: [app-network]

  auth:
    build:
      context: ../
      dockerfile: services/auth/dockerfile
    ports:
      - '${AUTH_SERVICE}:${AUTH_SERVICE}'
    env_file:
      - .env
    networks: [app-network]

  invite:
    build:
      context: ../
      dockerfile: services/invite/dockerfile
    ports:
      - '${INVITE_SERVICE}:${INVITE_SERVICE}'
    env_file:
      - .env
    networks: [app-network]

  metrics:
    build:
      context: ../
      dockerfile: services/metrics/dockerfile
    ports:
      - '${METRICS_SERVICE}:${METRICS_SERVICE}'
    env_file:
      - .env
    networks: [app-network]

  org:
    build:
      context: ../
      dockerfile: services/org/dockerfile
    ports:
      - '${ORG_SERVICE}:${ORG_SERVICE}'
    env_file:
      - .env
    networks: [app-network]

  users:
    build:
      context: ../
      dockerfile: services/users/dockerfile
    ports:
      - '${USERS_SERVICE}:${USERS_SERVICE}'
    env_file:
      - .env
    networks: [app-network]

networks:
  app-network:
    external: true
    name: qucore_auth_network
