services:
  audit:
    build:
      context: ../services/audit
      dockerfile: dockerfile
    volumes:
      - ../services/audit/src:/app/src
      - ../services/audit/package.json:/app/package.json
      - ../services/audit/package-lock.json:/app/package-lock.json
      - ../libs:/app/libs
    command: npm run dev
    ports:
      - '${AUDIT_SERVICE}:${AUDIT_SERVICE}'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  auth:
    build:
      context: ../services/auth
      dockerfile: dockerfile
    volumes:
      - ../services/auth/src:/app/src
      - ../services/auth/package.json:/app/package.json
      - ../services/auth/package-lock.json:/app/package-lock.json
      - ../libs:/app/libs
    command: npm run dev
    ports:
      - '${AUTH_SERVICE}:${AUTH_SERVICE}'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  invite:
    build:
      context: ../services/invite
      dockerfile: dockerfile
    volumes:
      - ../services/invite/src:/app/src
      - ../services/invite/package.json:/app/package.json
      - ../services/invite/package-lock.json:/app/package-lock.json
      - ../libs:/app/libs
    command: npm run dev
    ports:
      - '${INVITE_SERVICE}:${INVITE_SERVICE}'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  metrics:
    build:
      context: ../services/metrics
      dockerfile: dockerfile
    volumes:
      - ../services/metrics/src:/app/src
      - ../services/metrics/package.json:/app/package.json
      - ../services/metrics/package-lock.json:/app/package-lock.json
      - ../libs:/app/libs
    command: npm run dev
    ports:
      - '${METRICS_SERVICE}:${METRICS_SERVICE}'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  org:
    build:
      context: ../services/org
      dockerfile: dockerfile
    volumes:
      - ../services/org/src:/app/src
      - ../services/org/package.json:/app/package.json
      - ../services/org/package-lock.json:/app/package-lock.json
      - ../libs:/app/libs
    command: npm run dev
    ports:
      - '${ORG_SERVICE}:${ORG_SERVICE}'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  users:
    build:
      context: ../services/users
      dockerfile: dockerfile
    volumes:
      - ../services/users/src:/app/src
      - ../services/users/package.json:/app/package.json
      - ../services/users/package-lock.json:/app/package-lock.json
      - ../libs:/app/libs
    command: npm run dev
    ports:
      - '${USERS_SERVICE}:${USERS_SERVICE}'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
